// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	UserID       int64          `json:"user_id"`
	WeeklyLimit  pgtype.Numeric `json:"weekly_limit"`
	MonthlyLimit pgtype.Numeric `json:"monthly_limit"`
}

type Category struct {
	ID        pgtype.UUID `json:"id"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	Icon      string      `json:"icon"`
	IsSystem  bool        `json:"is_system"`
	SortOrder int32       `json:"sort_order"`
}

type Transaction struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDeleted  bool               `json:"is_deleted"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Currency   string             `json:"currency"`
}

type User struct {
	TgID      int64              `json:"tg_id"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
