// Code generated by sqlc. DO NOT EDIT.

package repository

import "github.com/jackc/pgx/v5/pgtype"

type User struct {
	TgID      int64              `json:"tg_id"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        pgtype.UUID `json:"id"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
	Icon      string      `json:"icon"`
	IsSystem  bool        `json:"is_system"`
	SortOrder int32       `json:"sort_order"`
}

type Budget struct {
	UserID       int64          `json:"user_id"`
	DailyLimit   pgtype.Numeric `json:"daily_limit"`
	WeeklyLimit  pgtype.Numeric `json:"weekly_limit"`
	MonthlyLimit pgtype.Numeric `json:"monthly_limit"`
}
