// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package repository

import "context"

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (tg_id, currency, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (tg_id) DO UPDATE
    SET updated_at = NOW()
RETURNING tg_id, currency, created_at, updated_at
`

type UpsertUserParams struct {
	TgID     int64  `json:"tg_id"`
	Currency string `json:"currency"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.TgID, arg.Currency)
	var i User
	err := row.Scan(
		&i.TgID,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetsByUserId = `-- name: GetBudgetsByUserId :one
SELECT user_id, daily_limit, weekly_limit, monthly_limit
FROM budgets
WHERE user_id = $1
`

func (q *Queries) GetBudgetsByUserId(ctx context.Context, userID int64) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetsByUserId, userID)
	var i Budget
	err := row.Scan(
		&i.UserID,
		&i.DailyLimit,
		&i.WeeklyLimit,
		&i.MonthlyLimit,
	)
	return i, err
}

const getCategoriesByUserId = `-- name: GetCategoriesByUserId :many
SELECT id, user_id, name, color, icon, is_system, sort_order
FROM categories
WHERE user_id = $1 OR is_system = true
ORDER BY sort_order ASC
`

func (q *Queries) GetCategoriesByUserId(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.IsSystem,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
